// utils.js — shared helpers (ported from the original js/utils.js + inline scripts)

const FEATURE_MAP = {
  "air bag": "Airbags",
  "driver air bag": "Driver Airbag",
  "passenger air bag": "Passenger Airbag",
  "side air bag": "Side Airbags",
  "air conditioning": "Air Conditioning",
  "am/fm stereo": "AM/FM Stereo",
  "cruise control": "Cruise Control",
  "interval wipers": "Interval Wipers",
  "power steering": "Power Steering",
  "power brakes": "Power Brakes",
  "tilt wheel": "Tilt Wheel",
  "trip odometer": "Trip Odometer",
  "power driver's seat": "Power Driver Seat",
  "power driver seat": "Power Driver Seat",
  "power passenger seat": "Power Passenger Seat",
  "cloth interior": "Cloth Interior",
  "leather interior": "Leather Interior",
  "power door locks": "Power Door Locks",
  "power mirrors": "Power Mirrors",
  "power windows": "Power Windows",
  bluetooth: "Bluetooth",
  "backup camera": "Backup Camera",
  "rear view camera": "Backup Camera",
  navigation: "Navigation",
  sunroof: "Sunroof",
  moonroof: "Moonroof",
  "keyless entry": "Keyless Entry",
  "remote start": "Remote Start",
  "heated seats": "Heated Seats",
  "alloy wheels": "Alloy Wheels",
  abs: "ABS",
};

const toKey = (s) =>
  String(s || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");

export function cleanFeatures(features) {
  if (!Array.isArray(features)) return [];
  const out = [];
  const seen = new Set();
  for (const f of features) {
    const key = toKey(f);
    if (!key) continue;
    const label = FEATURE_MAP[key] || String(f).trim();
    const dedupeKey = toKey(label);
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);
    out.push(label);
  }
  return out;
}

// Ensure an image path is absolute so it resolves from any route (e.g. /car/5).
export function imgPath(p) {
  const s = String(p || "");
  if (!s) return "";
  if (/^https?:\/\//.test(s) || s.startsWith("/")) return s;
  return "/" + s.replace(/^\.?\//, "");
}

// Small grid thumbnail for a car image (generated by scripts/make-thumbs.mjs).
// Falls back to the full image if it isn't a local /assets/cars/ photo.
export function thumbPath(p) {
  const s = imgPath(p);
  const m = s.match(/^\/assets\/cars\/([^/]+)$/);
  if (!m) return s;
  return `/assets/cars/thumb/${m[1].replace(/\.png$/i, ".jpg")}`;
}

export function normalizeCar(raw, idx = 0) {
  const r = raw && typeof raw === "object" ? raw : {};
  const id = r.id ?? r.stock ?? r.vin ?? idx + 1;
  return {
    ...r, // keep every original field (status, carfax, financing, description, fuel…)
    id: String(id),
    make: (r.make ?? "").toString(),
    model: (r.model ?? "").toString(),
    year: r.year ?? "",
    price: r.price ?? "",
    mileage: r.mileage ?? "",
    color: (r.color ?? "").toString(),
    engine: (r.engine ?? "").toString(),
    transmission: (r.transmission ?? "").toString(),
    stock: (r.stock ?? "").toString(),
    vin: (r.vin ?? "").toString(),
    img: imgPath(r.img ?? ""),
    thumb: thumbPath(r.img ?? ""),
    images: Array.isArray(r.images) ? r.images.filter(Boolean).map(imgPath) : [],
    features: cleanFeatures(r.features),
  };
}

// Neutral placeholder used when an image fails to load (broken/missing file).
export const IMG_FALLBACK =
  "data:image/svg+xml;charset=utf-8," +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='480' height='300' viewBox='0 0 480 300'><rect width='480' height='300' fill='#101114'/><path d='M120 190h240l-30-70a20 20 0 0 0-19-13H169a20 20 0 0 0-19 13z' fill='#1f2027'/><circle cx='170' cy='195' r='18' fill='#101114' stroke='#2c2d35' stroke-width='6'/><circle cx='330' cy='195' r='18' fill='#101114' stroke='#2c2d35' stroke-width='6'/><text x='240' y='250' fill='#5a5b63' font-family='sans-serif' font-size='16' text-anchor='middle'>Image unavailable</text></svg>`,
  );

// Use as an <img onError={onImgError}> handler — swaps to the placeholder once.
export function onImgError(e) {
  const el = e.currentTarget;
  if (el.dataset.fallback) return;
  el.dataset.fallback = "1";
  el.src = IMG_FALLBACK;
}

export const normalize = (v) => String(v ?? "").toLowerCase().trim();

export const toNum = (v) => {
  if (v === "" || v === null || v === undefined) return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

export function fuelType(c) {
  const explicit = c.fuel || c.fuelType || c.fuel_type;
  if (explicit) return String(explicit);
  const m = `${c.make ?? ""} ${c.model ?? ""} ${c.engine ?? ""}`;
  if (/hybrid/i.test(m)) return "Hybrid";
  if (/electric|\bev\b|tesla/i.test(m)) return "Electric";
  if (/diesel/i.test(m)) return "Diesel";
  return "Gas";
}

// Body style inferred from the model string (the feed spells it out, e.g.
// "Cherokee Trailhawk Sport Utility 4D") with a make/model fallback list.
const STYLE_RULES = [
  [/sport utility|\bsuv\b|crossover/i, "SUV"],
  [/pickup|\btruck\b|crew cab|regular cab|extended cab|silverado|\bram \d|f-?150|sierra|tacoma|tundra|frontier|ranger|colorado/i, "Truck"],
  [/minivan|\bvan\b|caravan|sienna|odyssey|sedona|pacifica|transit/i, "Van"],
  [/coupe|\bconvertible\b|mustang|challenger|camaro|veloster/i, "Coupe"],
  [/wagon|hatchback|outback sport/i, "Wagon"],
  [/sedan|\bsdn\b/i, "Sedan"],
];

export function bodyStyle(c) {
  if (c.body || c.bodyStyle) return String(c.body || c.bodyStyle);
  const hay = `${c.make ?? ""} ${c.model ?? ""}`;
  for (const [re, label] of STYLE_RULES) if (re.test(hay)) return label;
  return "Sedan";
}

// Price buckets used by the "Shop by price" tiles and /inventory?price= links.
export const PRICE_BANDS = [
  { key: "u8",     label: "Under $8,000",     min: 0,     max: 7999 },
  { key: "8-12",   label: "$8,000 – $12,000", min: 8000,  max: 11999 },
  { key: "12-20",  label: "$12,000 – $20,000", min: 12000, max: 19999 },
  { key: "o20",    label: "Over $20,000",     min: 20000, max: Infinity },
];

export function priceBand(c) {
  const p = toNum(c.price);
  if (p === null) return null;
  return PRICE_BANDS.find((b) => p >= b.min && p <= b.max) || null;
}

export function isSold(c) {
  return (c.status || "available") === "sold";
}

// Price-drop ("deal") vehicles carry an `oldPrice` above the current asking price.
export function isDeal(c) {
  if (isSold(c)) return false;
  const p = toNum(c.price);
  const o = toNum(c.oldPrice);
  return p !== null && o !== null && o > p;
}

// Dollars off the original asking price, or null when the car is not discounted.
export function savings(c) {
  if (!isDeal(c)) return null;
  return toNum(c.oldPrice) - toNum(c.price);
}

// Inventory badge (matches collection.html inline logic)
export function badgeFor(c) {
  if (isSold(c)) return { text: "SOLD", cls: "badge-sold" };
  const s = savings(c);
  if (s !== null) return { text: `SAVE $${s.toLocaleString()}`, cls: "badge-deal" };
  const p = toNum(c.price);
  const m = toNum(c.mileage);
  if (p !== null && p <= 8000) return { text: "SPECIAL", cls: "badge-special" };
  if (m !== null && m <= 70000) return { text: "LOW MILES", cls: "badge-low" };
  return { text: "FEATURED", cls: "badge-featured" };
}

export const carName = (c) =>
  [c.year, c.make, c.model].filter(Boolean).join(" ").trim();

export const fmtPrice = (v) => {
  const n = toNum(v);
  return n !== null ? `$${n.toLocaleString()}` : v ?? "";
};

export const fmtMiles = (v) => {
  const n = toNum(v);
  return n !== null ? n.toLocaleString() : v ?? "";
};

// "128k miles" — the short mileage form used on listing cards.
export function milesShort(c) {
  const m = toNum(c.mileage);
  if (m === null) return null;
  return m >= 1000 ? `${Math.round(m / 1000)}k miles` : `${m.toLocaleString()} miles`;
}

// Rough monthly estimate: 72 months at 9.9% APR with 10% down. Illustrative only.
export function monthlyEstimate(c, { months = 72, apr = 0.099, downPct = 0.1 } = {}) {
  const p = toNum(c.price);
  if (!p) return null;
  const principal = p * (1 - downPct);
  const r = apr / 12;
  const pay = (principal * r) / (1 - Math.pow(1 + r, -months));
  return Math.round(pay);
}

// Feature bullets for the card — the marketing-relevant ones, capped.
const FEATURE_PRIORITY = [
  /navigation/i, /leather/i, /sunroof|moonroof/i, /awd|4wd|four wheel|all wheel/i,
  /backup camera|rear camera/i, /heated seat/i, /bluetooth/i, /third row|3rd row/i,
  /alloy wheel/i, /remote start/i, /keyless/i, /cruise control/i,
];
export function topFeatures(c, limit = 4) {
  const list = Array.isArray(c.features) ? c.features : [];
  const picked = [];
  for (const re of FEATURE_PRIORITY) {
    const hit = list.find((x) => re.test(x) && !picked.includes(x));
    if (hit) picked.push(hit);
    if (picked.length >= limit) break;
  }
  for (const x of list) {
    if (picked.length >= limit) break;
    if (!picked.includes(x)) picked.push(x);
  }
  return picked.slice(0, limit);
}

// Feature groups for the detail page — the flat feed list read as sections.
const FEATURE_GROUPS = [
  ["Safety", /air ?bag|abs|brake assist|stability|traction|blind spot|lane |collision|alarm|immobilizer|child|latch|tire pressure|rollover|security/i],
  ["Comfort & Interior", /seat|leather|climate|air conditioning|heated|cooled|memory|lumbar|armrest|cup holder|vanity|console|floor mat|steering wheel|tilt|telescop|cruise control|keyless|remote start|power window|power door|trunk|cargo/i],
  ["Entertainment", /stereo|radio|audio|speaker|cd |mp3|bluetooth|usb|aux|satellite|navigation|touch ?screen|premium sound|smart ?device|apple|android/i],
  ["Exterior", /wheel|tire|sunroof|moonroof|roof rack|spoiler|fog|headlight|daytime|mirror|window tint|bumper|running board|tow|trailer|bed liner/i],
  ["Mechanical", /engine|transmission|4wd|awd|drive|suspension|axle|differential|cylinder|turbo|hybrid|battery|power steering|power brakes|gvwr/i],
];

export function groupFeatures(c) {
  const list = Array.isArray(c.features) ? c.features : [];
  const groups = FEATURE_GROUPS.map(([name]) => ({ name, items: [] }));
  const other = [];
  for (const item of list) {
    const i = FEATURE_GROUPS.findIndex(([, re]) => re.test(item));
    if (i >= 0) groups[i].items.push(item);
    else other.push(item);
  }
  if (other.length) groups.push({ name: "Additional", items: other });
  return groups.filter((g) => g.items.length);
}
