// utils.js — shared helpers (ported from the original js/utils.js + inline scripts)

const FEATURE_MAP = {
  "air bag": "Airbags",
  "driver air bag": "Driver Airbag",
  "passenger air bag": "Passenger Airbag",
  "side air bag": "Side Airbags",
  "air conditioning": "Air Conditioning",
  "am/fm stereo": "AM/FM Stereo",
  "cruise control": "Cruise Control",
  "interval wipers": "Interval Wipers",
  "power steering": "Power Steering",
  "power brakes": "Power Brakes",
  "tilt wheel": "Tilt Wheel",
  "trip odometer": "Trip Odometer",
  "power driver's seat": "Power Driver Seat",
  "power driver seat": "Power Driver Seat",
  "power passenger seat": "Power Passenger Seat",
  "cloth interior": "Cloth Interior",
  "leather interior": "Leather Interior",
  "power door locks": "Power Door Locks",
  "power mirrors": "Power Mirrors",
  "power windows": "Power Windows",
  bluetooth: "Bluetooth",
  "backup camera": "Backup Camera",
  "rear view camera": "Backup Camera",
  navigation: "Navigation",
  sunroof: "Sunroof",
  moonroof: "Moonroof",
  "keyless entry": "Keyless Entry",
  "remote start": "Remote Start",
  "heated seats": "Heated Seats",
  "alloy wheels": "Alloy Wheels",
  abs: "ABS",
};

const toKey = (s) =>
  String(s || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");

export function cleanFeatures(features) {
  if (!Array.isArray(features)) return [];
  const out = [];
  const seen = new Set();
  for (const f of features) {
    const key = toKey(f);
    if (!key) continue;
    const label = FEATURE_MAP[key] || String(f).trim();
    const dedupeKey = toKey(label);
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);
    out.push(label);
  }
  return out;
}

// Ensure an image path is absolute so it resolves from any route (e.g. /car/5).
export function imgPath(p) {
  const s = String(p || "");
  if (!s) return "";
  if (/^https?:\/\//.test(s) || s.startsWith("/")) return s;
  return "/" + s.replace(/^\.?\//, "");
}

// Small grid thumbnail for a car image (generated by scripts/make-thumbs.mjs).
// Falls back to the full image if it isn't a local /assets/cars/ photo.
export function thumbPath(p) {
  const s = imgPath(p);
  const m = s.match(/^\/assets\/cars\/([^/]+)$/);
  if (!m) return s;
  return `/assets/cars/thumb/${m[1].replace(/\.png$/i, ".jpg")}`;
}

export function normalizeCar(raw, idx = 0) {
  const r = raw && typeof raw === "object" ? raw : {};
  const id = r.id ?? r.stock ?? r.vin ?? idx + 1;
  return {
    ...r, // keep every original field (status, carfax, financing, description, fuel…)
    id: String(id),
    make: (r.make ?? "").toString(),
    model: (r.model ?? "").toString(),
    year: r.year ?? "",
    price: r.price ?? "",
    mileage: r.mileage ?? "",
    color: (r.color ?? "").toString(),
    engine: (r.engine ?? "").toString(),
    transmission: (r.transmission ?? "").toString(),
    stock: (r.stock ?? "").toString(),
    vin: (r.vin ?? "").toString(),
    img: imgPath(r.img ?? ""),
    thumb: thumbPath(r.img ?? ""),
    images: Array.isArray(r.images) ? r.images.filter(Boolean).map(imgPath) : [],
    features: cleanFeatures(r.features),
  };
}

// Neutral placeholder used when an image fails to load (broken/missing file).
export const IMG_FALLBACK =
  "data:image/svg+xml;charset=utf-8," +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='480' height='300' viewBox='0 0 480 300'><rect width='480' height='300' fill='#0a1c30'/><path d='M120 190h240l-30-70a20 20 0 0 0-19-13H169a20 20 0 0 0-19 13z' fill='#16314a'/><circle cx='170' cy='195' r='18' fill='#0a1c30' stroke='#22405c' stroke-width='6'/><circle cx='330' cy='195' r='18' fill='#0a1c30' stroke='#22405c' stroke-width='6'/><text x='240' y='250' fill='#3a5a78' font-family='sans-serif' font-size='16' text-anchor='middle'>Image unavailable</text></svg>`,
  );

// Use as an <img onError={onImgError}> handler — swaps to the placeholder once.
export function onImgError(e) {
  const el = e.currentTarget;
  if (el.dataset.fallback) return;
  el.dataset.fallback = "1";
  el.src = IMG_FALLBACK;
}

export const normalize = (v) => String(v ?? "").toLowerCase().trim();

export const toNum = (v) => {
  if (v === "" || v === null || v === undefined) return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

export function fuelType(c) {
  const explicit = c.fuel || c.fuelType || c.fuel_type;
  if (explicit) return String(explicit);
  const m = `${c.make ?? ""} ${c.model ?? ""} ${c.engine ?? ""}`;
  if (/hybrid/i.test(m)) return "Hybrid";
  if (/electric|\bev\b|tesla/i.test(m)) return "Electric";
  if (/diesel/i.test(m)) return "Diesel";
  return "Gas";
}

export function isSold(c) {
  return (c.status || "available") === "sold";
}

// Inventory badge (matches collection.html inline logic)
export function badgeFor(c) {
  if (isSold(c)) return { text: "SOLD", cls: "badge-sold" };
  const p = toNum(c.price);
  const m = toNum(c.mileage);
  if (p !== null && p <= 8000) return { text: "SPECIAL", cls: "badge-special" };
  if (m !== null && m <= 70000) return { text: "LOW MILES", cls: "badge-low" };
  return { text: "FEATURED", cls: "badge-featured" };
}

export const carName = (c) =>
  [c.year, c.make, c.model].filter(Boolean).join(" ").trim();

export const fmtPrice = (v) => {
  const n = toNum(v);
  return n !== null ? `$${n.toLocaleString()}` : v ?? "";
};

export const fmtMiles = (v) => {
  const n = toNum(v);
  return n !== null ? n.toLocaleString() : v ?? "";
};
